server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: aaron
    password: aaron1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # create, update, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
    
  jackson:
    serialization:
      fail-on-empty-beans: false
  
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
# com.mysql.cj.jdbc.Driver
# com.mysql.jdbc.Driver
# datasource 의 mysql 드라이버에 cj가 들어간 이유는 mysql 6점대 이상 버전부터는 해당 드라이버를 사용하고 그 이전 드라이버는 cj가 없는 com.mysql.jdbc.Driver를 사용한다.


# org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# 엔티티를 만들 때 변수명 그대로 DB에 필드를 만들어 준다.
# org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
# 엔티티를 만들 때 변수명에 언더스코어를 붙여준다. 예) createDate -> create_date


# use-new-id-generator-mappings 는 mysql로 말하면 auto_increment 오라클로 말하면 시퀀스를 어떤식으로 사용할지 방식을 결정하는 것인데 false를 하면 jpa가 사용하는 기본 넘버링 전략을 따라가지 않는다는 뜻이고 true를 하면 기본 넘버링 전략을 따라간다는 뜻이다.


# jackson.serialization.fail-on-empty-beans:false
# Lazy-loading으로 인해 empty-beans이 생길 수 있다. 너그럽게 빈 객체를 허락해주는 옵션이다.